name: CI/CD Pipeline with Test Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Jest Tests and Save Output
        run: npm run test -- --json > test-output.json

      - name: Upload Jest Test Output
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: test-output.json

  ai-analysis:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download Jest Test Output
        uses: actions/download-artifact@v4
        with:
          name: test-output

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Prepare and Send Test Results to AI
        run: |
          TEST_OUTPUT=$(cat test-output.json | jq -Rs .)

          jq -n --arg model "llama3.2:latest" \
                --arg prompt "Analyze the following Jest test results and provide:\n- Summary of pass/fail\n- Possible reasons for failure\n- Suggestions to fix\n- Code improvement tips\n\nTest Results:\n$TEST_OUTPUT" \
                --argjson stream false \
                '{model: $model, prompt: $prompt, stream: $stream}' > prompt.json

          curl -s -X POST https://2daf-14-99-175-222.ngrok-free.app/api/generate \
            -H "Content-Type: application/json" \
            -d @prompt.json > ai-analysis-result.json

      - name: Upload AI Analysis Result
        uses: actions/upload-artifact@v4
        with:
          name: ai-analysis-result
          path: ai-analysis-result.json

  notify:
    needs: [test, ai-analysis]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download AI Analysis Result
        uses: actions/download-artifact@v4
        with:
          name: ai-analysis-result

      - name: Read AI Analysis
        id: analysis
        run: |
          echo "Reading AI analysis..."
          echo "analysis_output<<EOF" >> $GITHUB_OUTPUT
          cat ai-analysis-result.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Slack Notification
        env:
          ANALYSIS_RESULT: ${{ steps.analysis.outputs.analysis_output }}
        run: |
          STATUS="✅ All tests passed!"
          if [ "${{ needs.test.result }}" == "failure" ]; then
            STATUS="🚨 Some tests failed!"
          fi

          curl -X POST -H 'Content-type: application/json' \
          --data "$(jq -n --arg text "$STATUS\n\nAI Code Suggestions:\n$ANALYSIS_RESULT" '{text: $text}')" \
          https://hooks.slack.com/services/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
