name: CI/CD Pipeline with Test Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Jest Tests and Save Output
        run: npm run test -- --json --outputFile=test-output.json

      - name: Print Jest Output (Debug)
        run: cat test-output.json

      - name: Upload Jest Test Output
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: test-output.json

  ai-analysis:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download Jest Test Output
        uses: actions/download-artifact@v4
        with:
          name: test-output

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Prepare and Send Test Results to AI
        run: |
          echo "Reading test output..."
          TEST_OUTPUT=$(cat test-output.json)

          PROMPT="Analyze the following Jest test results and provide:
          - Summary of pass/fail
          - Possible reasons for failure
          - Suggestions to fix
          - Code improvement tips

          Test Results:
          $TEST_OUTPUT"

          jq -n --arg model "llama3.2:latest" \
                --arg prompt "$PROMPT" \
                --argjson stream false \
                '{model: $model, prompt: $prompt, stream: $stream}' > prompt.json

          echo "Sending prompt to AI endpoint..."
          curl -v -X POST https://604b-14-99-175-222.ngrok-free.app/api/ainanalyze/ \
            -H "Content-Type: application/json" \
            -d @prompt.json > ai-analysis-result.json

      - name: Print AI Analysis Result (Debug)
        run: cat ai-analysis-result.json

      - name: Upload AI Analysis Result
        uses: actions/upload-artifact@v4
        with:
          name: ai-analysis-result
          path: ai-analysis-result.json
          

