name: CI/CD Pipeline with Test Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Jest Tests and Save Output
        run: npm run test -- --json > test-output.json

      - name: Upload Jest Test Output
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: test-output.json

  ai-analysis:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download Jest Test Output
        uses: actions/download-artifact@v4
        with:
          name: test-output

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Prepare and Send Test Results to AI
        run: |
          TEST_OUTPUT=$(cat test-output.json | jq -Rs .)

          jq -n --arg model "llama3.2:latest" \
                --arg prompt "Analyze the following Jest test results and provide:\n- Summary of pass/fail\n- Possible reasons for failure\n- Suggestions to fix\n- Code improvement tips\n\nTest Results:\n$TEST_OUTPUT" \
                --argjson stream false \
                '{model: $model, prompt: $prompt, stream: $stream}' > prompt.json

          curl --location 'https://2daf-14-99-175-222.ngrok-free.app/api/generate' \
                --header 'Content-Type: application/json' \
                --data '{
                  "model": "llama3.2:latest",
                  "prompt": "hiii",
                  "stream": false
                  }' > ai-analysis-result.json

      - name: Output AI Analysis
        run: cat ai-analysis-result.json

  notify:
    if: failure() && needs.test.result == 'failure'
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification for Test Failures
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "🚨 Jest tests failed in CI! Please check the pipeline for details."}' \
          https://hooks.slack.com/services/your/slack/webhook/url
